source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 8.0.0"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bootsnap", require: false

# Serialization
gem "alba"
gem "oj"

# HTTP Client
gem "faraday"
gem "faraday-retry"

# RabbitMQ
gem "bunny"

# Testing
group :development, :test do
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers"
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
end

group :test do
  gem "simplecov", require: false
  gem "vcr"
  gem "webmock"
end

# Linting
group :development do
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
  gem "rubocop-performance", require: false
end
